# Generated by Django 5.1.1 on 2024-09-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('product_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=25)),
                ('product_description', models.CharField(max_length=255)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('product_units', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='authentication.userauthentication')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
